# Generated by Django 4.2.4 on 2023-09-03 12:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('entity', models.CharField(choices=[('National', 'National'), ('County', 'County'), ('Other', 'Other')], max_length=150)),
                ('institution', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=150)),
                ('file_from', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('office_to', models.CharField(choices=[('Office_of_The_Governor', 'Office of The Governor'), ('Office_of_The_Deputy_Governor', 'Office of The Deputy Governor')], max_length=200)),
                ('county', models.CharField(blank=True, choices=[('Mandera_County', 'Mandera County'), ('Wajir_County', 'Wajir County'), ('Garissa_County', 'Garissa County')], max_length=150, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])])),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Received',
                'verbose_name_plural': 'Received',
            },
        ),
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('sent_to', models.CharField(choices=[('National', 'National'), ('County', 'County'), ('Other', 'Other')], max_length=150)),
                ('institution', models.CharField(max_length=100)),
                ('date_sent', models.DateField()),
                ('office_from', models.CharField(choices=[('Office_of_The_Governor', 'Office of The Governor'), ('Office_of_The_Deputy_Governor', 'Office of The Deputy Governor')], max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sent',
                'verbose_name_plural': 'Sent',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_governor', models.BooleanField(default=False)),
                ('is_deputy_governor', models.BooleanField(default=False)),
                ('is_clerk', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
