# Generated by Django 4.2.4 on 2023-09-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_alter_sent_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
