# Generated by Django 4.2.4 on 2023-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0007_alter_received_county_alter_received_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='date_received',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sent',
            name='date_sent',
            field=models.DateField(max_length=10),
        ),
    ]
